### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gick** [gick/osm-vuejs#10]
# Front end
- [x] Intégrer la dernière version de la liste des arbres (odt Olivier)
- [x] Remplacer les composants liste espèce/genre/nom commun par des vue-select
- [x] Supprimer les liens entre les composants de selection Espèce/genre/non commun
- [ ] ~~Ne pas faire apparaitre le champ auteur dans Mes relevé~~ 
- [ ] Remplacer le disable par un hide pour le composant supprimer (Bad UI)
- [ ] Supprimer le menu hamburger
- [ ] Supprimer le titre Albiziapp pour gagner de la place
- [x] Rendre le champ Valider inactif dans les identifications tant que la photo n'a pas été prise
- [x] Bug : dans l'édition d'un relevé, si on fait annuler après avoir fait une modif, la modif est prise en compte
- [ ] Intégrer un bouton plus d'info pour donner les définitions précises des champs cf mail Olivier
- [x] Dans mes relevés : faire apparaitre arbre non renseigné si pas de genre ni d'espèce
- [x] Modifier les textes anglais Cancel et Tap here to add photo par des textes fr
- [x] Supprimer les champs hauteur et diamètre couronne
- [x] Modifier le design du champ confiance pour faire apparaitre qu'il concerne espèce et genre. 3 state toggle (Bad UI)
- [ ] Ajouter un label Espèce/Genre/Commun aux champs de la page d'édition de relevé (Bad UI)
- [x] Ajouter des posts /api/track pour les actions changement de page/annulation/choix d'une espèce/consultation d'un relevé
- [x] Supprimer la dépendance socket.io
- [x] Ajouter des posts /api/user pour le maintient de la session en cas de refresh
- [x] Ajouter une barre de statut footer sur la map (mission/points/chrono)
- [ ] Optimiser le build webpack pour les performance au premier chargement
- [x] Mode admin, l'ajout d'identification experte ne doit pas faire progresser la mission
- [x] Fin de mission identification experte freeze
- [x] Resize Prendre photo
- [x] Régler problème modification des relevé vert
- [x] Problème arboretum
- [ ] Problème reprise de session en cas de session non identifié
- [ ] Problème reprise de session non conforme (Iza)
- [ ] Custom chrono pour mission 5

# Back end
- [x] Changer la communication avec Folia Socket.io->SSE
- [x] Intégrer un timeout dans l'execution de Folia avec affichage d'une erreur si l'opération est trop longue
- [x] Déléguer la gestion des scores au back end
- [x] Envoyer des notifs pusher lors de changement de score suite à une validation/confirmation
- [x] Intégrer la gestion des status (tableau a double entrée)
- [x] Créer une nouvelle collection user pour garder la trace des scores/trophés
- [x] Gérer la reprise de session lors d'un refresh de la page /api/user
- [x] Rendre possible la modification dans Albiziapp des enregistrement OSM
- [x] Intégrer la gestion des traces de l'activité utilisateur /api/track
- [ ] Déployer sur le nouveau serveur du LIUM si possible
- [ ] Automatiser le déployement

# Experiment
- [ ] Investiguer MongoChart pour l'analyse des traces
- [ ] Investiguer LogRocket ....
- [ ] Vérifier la consistance des traces (association user->action->activite->releve)
